name: Deploy to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        env:
          AWS_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region $AWS_REGION

      - name: Update kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name test-practice --kubeconfig kubeconfig.yml
          
      - name: Store Kubeconfig in GitHub Actions Secret
        run: |
          gh secrets set KUBECONFIG - < kubeconfig.yml

      - name: Clean Up
        run: |
          # Clean up sensitive data
          rm kubeconfig.yml

