name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Sonarcloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         args: >
              -Dsonar.organization=yogeshgandamaneni
              -Dsonar.projectKey=vprofile
              -Dsonar.python.coverage.reportPaths=coverage.xml
      

      - name: Running the Python script
        run: python ./src/Selenium_test.py
        
     
