name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Sonarcloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
         args: >
              -Dsonar.organization=sonartestw
              -Dsonar.projectkey=vprofile
              -Dsonar.python.coverage.reportPaths=coverage.xml
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed   

      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

      - name: check chrome version
        run: google-chrome --version
             
      - name: Install xvfb
        run: |
           sudo apt update -y
           sudo apt-get install xvfb -y

      - name: Running the Python script
        run: python ./src/Selenium_test.py
        
     
