name: Update Kubernetes 

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
       region: us-east-1
       cluster: test-practice

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        env:
          AWS_REGION: us-east-1
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region $AWS_REGION
          
      - name: Update kubeconfig
        run: |
          aws eks --region $region update-kubeconfig --name $cluster
          ls

   #   - name: update config
     #   run: |
      #    echo "$KUBECONFIG" > kubeconfig
      #    chmod 600 kubeconfig
        #  export KUBECONFIG=$PWD/kubeconfig
          
   
          
      - name: getnodes
        run: kubectl get nodes

        

   
