name: Update Kubernetes 

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: update config
        run: |
          echo "$KUBECONFIG" > kubeconfig
          chmod 600 kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          cat kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          
      - name: getnodes
        run: kubectl get nodes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        

   
