name: Update Kubernetes 

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

      - name: update config
        run: |
          echo "$KUBECONFIG" > kubeconfig
          chmod 600 kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          
      - name: getnodes
        run: |
             pwd
             ls
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
          
      - name: getnodes
        run: kubectl get nodes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        

   
