name: Terraform Apply and Destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install apache2
      run: |
         sudo apt update
         sudo apt install apache2

    # Optional: If you wish to destroy the resources after testing:
    # - name: Terraform Destroy
    #   run: terraform apply -auto-approve
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

